# Generated by Django 5.1.4 on 2025-01-14 18:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFunds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=254, verbose_name='Name of the mutual fund')),
                ('fund_type', models.CharField(choices=[('E', 'Equity'), ('D', 'Debt'), ('H', 'Hybrid')], max_length=1)),
                ('nav', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Net Asset Value')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('name', 'fund_type')},
            },
        ),
        migrations.CreateModel(
            name='UserInvestments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('units', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of units')),
                ('mutual_fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='accountings.mutualfunds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'mutual_fund')},
            },
        ),
    ]
