# Generated by Django 5.1.4 on 2025-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunds',
            name='name',
            field=models.CharField(max_length=254, unique=True, verbose_name='Name of the mutual fund'),
        ),
    ]
