# Generated by Django 5.1.4 on 2025-01-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0002_alter_mutualfunds_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunds',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Name of the mutual fund'),
        ),
        migrations.AlterUniqueTogether(
            name='mutualfunds',
            unique_together={('name', 'fund_type')},
        ),
    ]
