# Generated by Django 5.1.4 on 2025-01-14 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0003_alter_mutualfunds_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinvestments',
            unique_together={('user', 'mutual_fund')},
        ),
    ]
