# Generated by Django 5.1.4 on 2025-01-14 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountings', '0004_alter_userinvestments_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunds',
            name='nav',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Net Asset Value'),
        ),
        migrations.AlterField(
            model_name='userinvestments',
            name='units',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of units'),
        ),
    ]
